config/routes.rb
BuildStatus::Application.routes.draw do

  match 'update_build' => 'builds#update_build', :via => :post
  match 'branches/:branch_name/last_good_revision' => 'branches#last_good_revision', :via => :get
  resources :branches do
    resources :builds
    resources :revisions
  end

  root :to => 'home#index'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :builds, :conditions => {:enabled => true}
  has_many :all_builds, :class_name => 'Build', :order => 'enabled DESC'
  has_many :revisions, :order => 'created_at DESC'

  attr_accessible :name

  def display_revisions
    revisions.all(:limit => 10)
  end

  def last_good_revision
    revs = []
    build_ids = builds.collect(&:id)

    revisions.each do |rev|
      revision_builds = rev.build_results.collect(&:build_id)
      next unless revision_builds.sort == build_ids.sort
      revs << rev if rev.good?
    end

    if revs.first
      revs.first.sha
    end
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, :notice => 'Branch was successfully created.' }
        format.json { render :json => @branch, :status => :created, :location => @branch }
      else
        format.html { render :action => "new" }
        format.json { render :json => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, :notice => 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    branch = Branch.find(params[:id])
    branch.destroy

    redirect_to :action => :index
  end

  def last_good_revision
    @branch = Branch.find_by_name params[:branch_name]
    render :text => @branch.last_good_revision
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.haml
= form_for @branch do |f|
  -if @branch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@branch.errors.count, "error")} prohibited this branch from being saved:"
      %ul
        - @branch.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save', :class => 'btn btn-success'

app/views/branches/edit.html.haml
%h1 Editing branch

= render 'form'

= link_to 'Show', @branch
\|
= link_to 'Back', branches_path

app/views/branches/index.html.haml
%h1 Listing branches

.row
  .span2
    %h5 Name
- @branches.each do |branch|
  .row
    .span1
      = branch.name
    .span3
      = link_to 'View builds', branch_builds_path(branch)
      = link_to 'Show', branch
      = link_to 'Edit', edit_branch_path(branch)
      = link_to 'Destroy', branch, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger'
%br

= link_to 'New Branch', new_branch_path

app/views/branches/new.html.haml
%h1 New branch

= render 'form'

= link_to 'Back', branches_path

app/views/branches/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @branch.name

= link_to 'Edit', edit_branch_path(@branch)
\|
= link_to 'Back', branches_path