config/routes.rb
BuildStatus::Application.routes.draw do

  match 'update_build' => 'builds#update_build', :via => :post
  match 'branches/:branch_name/last_good_revision' => 'branches#last_good_revision', :via => :get
  resources :branches do
    resources :builds
    resources :revisions
  end

  root :to => 'home#index'

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :branch

  attr_accessible :branch_id, :name, :enabled
end

app/controllers/builds_controller.rb
require 'json'

class BuildsController < ApplicationController
  # GET /builds
  # GET /builds.json
  def index
    branch = Branch.find(params[:branch_id])
    @builds = branch.all_builds

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @builds }
    end
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
    @build = Build.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @build }
    end
  end

  # GET /builds/new
  # GET /builds/new.json
  def new
    @build = Build.new
    @branch = Branch.find(params[:branch_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @build }
    end
  end

  # GET /builds/1/edit
  def edit
    @build = Build.find(params[:id])
    @branch = Branch.find(params[:branch_id])
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(params[:build])
    branch = Branch.find(params[:branch_id])
    @build.branch = branch

    respond_to do |format|
      if @build.save
        format.html { redirect_to [branch, @build], :notice => 'Build was successfully created.' }
        format.json { render :json => @build, :status => :created, :location => @build }
      else
        format.html { render :action => "new" }
        format.json { render :json => @build.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /builds/1
  # PUT /builds/1.json
  def update
    @build = Build.find(params[:id])
    @build.branch = Branch.find(params[:branch_id])

    respond_to do |format|
      if @build.update_attributes(params[:build])
        format.html { redirect_to :action => :index, :notice => 'Build was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @build.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    build = Build.find(params[:id])
    build.destroy
    redirect_to :action => :index
  end

  def update_build
    build_info = JSON.parse(params[:payload])

    if BuildUpdater.new.update_with(build_info)
      render :nothing => true
      return
    else
      render :nothing => true, :status => 422
      return
    end
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.haml
= form_for [@branch, @build] do |f|
  -if @build.errors.any?
    #error_explanation
      %h2= "#{pluralize(@build.errors.count, "error")} prohibited this build from being saved:"
      %ul
        - @build.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :enabled
    = f.check_box :enabled
  .actions
    = f.submit 'Save', :class => 'btn btn-success'

app/views/builds/edit.html.haml
%h1 Editing build

= render 'form'

= link_to 'Show', branch_build_path(@build)
\|
= link_to 'Back', branch_builds_path

app/views/builds/index.html.haml
%h1 Listing builds

.row
  .span1
    %h5 Name
  .span1
    %h5 Branch
  .span1
    %h5 Enabled
- @builds.each do |build|
  .row
    .span1
      = build.name
    .span1
      = build.branch_id
    .span1
      = build.enabled
    .span3
      = link_to 'Show', branch_build_path(build.branch, build)
      = link_to 'Edit', edit_branch_build_path(build.branch, build)
      = link_to 'Destroy', [build.branch, build], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger'

%br

= link_to 'New Build', new_branch_build_path

app/views/builds/new.html.haml
%h1 New build

= render 'form'

= link_to 'Back', branch_builds_path

app/views/builds/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @build.name
%p
  %b Branch:
  = @build.branch.name

= link_to 'Edit', edit_branch_build_path(@build)
\|
= link_to 'Back', branch_builds_path