config/routes.rb
BuildStatus::Application.routes.draw do

  match 'update_build' => 'builds#update_build', :via => :post
  match 'branches/:branch_name/last_good_revision' => 'branches#last_good_revision', :via => :get
  resources :branches do
    resources :builds
    resources :revisions
  end

  root :to => 'home#index'

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  has_many :build_results
  belongs_to :branch

  attr_accessible :branch_id, :sha

  GOOD = 'good'
  BAD = 'bad'
  UNKNOWN = 'unknown'

  def good?
    status == GOOD
  end

  def status
    return @status if @status

    builds = branch.builds
    branch_build_names = builds.collect(&:name)
    build_results = results_for(builds)
    revision_build_names = build_results.collect(&:build).collect(&:name)

    results = build_results.map(&:result)
    return @status = BAD if results.include? 'FAILURE'
    return @status = UNKNOWN if results.include? 'ABORTED'

    return @status = UNKNOWN if builds.empty?
    return @status = UNKNOWN unless branch_build_names.sort == revision_build_names.sort

    @status = GOOD
  end

  def wall_time
    results = results_for(branch.builds)
    return 0 if results.empty?

    start_time = results.sort_by(&:timestamp).first.timestamp
    endtime = results.map do |result|
      result.timestamp + result.build_time
    end.sort.last

    total_minutes = ((endtime - start_time) / 1000 / 60).to_i

    time_ago_in_words(total_minutes.minutes.ago)
  end

  def display_time
    results = results_for(branch.builds)
    times_in_minutes = results.map do |result|
      result.build_time.to_i / 1000 / 60
    end
    total_minutes = times_in_minutes.inject(0, :+)

    time_ago_in_words(total_minutes.minutes.ago)
  end

  protected

  def results_for(builds)
    build_results.where(:build_id => builds.map(&:id))
  end

end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  # GET /revisions
  # GET /revisions.json
  def index
    @revisions = Revision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @revisions }
    end
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
    @revision = Revision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @revision }
    end
  end

  # GET /revisions/new
  # GET /revisions/new.json
  def new
    @revision = Revision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @revision }
    end
  end

  # GET /revisions/1/edit
  def edit
    @revision = Revision.find(params[:id])
  end

  # POST /revisions
  # POST /revisions.json
  def create
    @revision = Revision.new(params[:revision])

    respond_to do |format|
      if @revision.save
        format.html { redirect_to @revision, :notice => 'Revision was successfully created.' }
        format.json { render :json => @revision, :status => :created, :location => @revision }
      else
        format.html { render :action => "new" }
        format.json { render :json => @revision.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /revisions/1
  # PUT /revisions/1.json
  def update
    @revision = Revision.find(params[:id])

    respond_to do |format|
      if @revision.update_attributes(params[:revision])
        format.html { redirect_to @revision, :notice => 'Revision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @revision.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/revisions/_form.html.haml
= form_for @revision do |f|
  -if @revision.errors.any?
    #error_explanation
      %h2= "#{pluralize(@revision.errors.count, "error")} prohibited this revision from being saved:"
      %ul
        - @revision.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/revisions/edit.html.haml
%h1 Editing revision

= render 'form'

= link_to 'Show', @revision
\|
= link_to 'Back', revisions_path

app/views/revisions/index.html.haml
%h1 Listing revisions

%table
  %tr
    %th
    %th
    %th

  - @revisions.each do |revision|
    %tr
      %td= link_to 'Show', revision
      %td= link_to 'Destroy', revision, :confirm => 'Are you sure?', :method => :delete

app/views/revisions/new.html.haml
%h1 New revision

= render 'form'

= link_to 'Back', revisions_path

app/views/revisions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_revision_path(@revision)
\|
= link_to 'Back', revisions_path